%This file was generated by Finch.

%{
Generated functions
%}
genfunction_0_fun = @(x,y,z,t) (sin(3*pi*x));
genfunction_0 = evaluate_genfun(genfunction_0_fun, grid_data.allnodes, 0);
genfunction_1_fun = @(x,y,z,t) (-2*pi*pi*sin(pi*x)*sin(pi*y));
genfunction_1 = evaluate_genfun(genfunction_1_fun, grid_data.allnodes, 0);
u = 'u';
Nvars = 0
f = genfunction_1;
function u = evaluate_genfun(genfun, pts, t)
    n = size(pts,2);
    dim = size(pts,1);
    u = zeros(n,1);
    x = 0;
    y = 0;
    z = 0;
    for i=1:n
        x = pts(1,i);
        if dim > 1
            y = pts(2,i);
            if dim > 2
                z = pts(3,i);
            end
        end
        u(i) = genfun(x,y,z,t);
    end
end

