%This file was generated by Finch.

%{
This is an example for 2D Poisson, Dirichlet bc.
%}
clear;


Utils;
Config;
Mesh;
Genfunction;
Problem;
Bilinear;
Linear;

u = LHS\RHS;


gxy = grid_data.allnodes';

X = gxy(:,1);
Y = gxy(:,2);

DT = delaunay(gxy);
Tu = triangulation(DT, X, Y, u);

figure();
trisurf(Tu, 'edgecolor', 'none')
view(2);


