%This file was generated by Finch.

%{
Problem info
%}
prob.bc_type = ['Dirichlet' ];
prob.bid = [1 ];
prob.bc_func = [[genfunction_0] ];
prob.ref_point = [];
prob.time_dependent = false;
prob.end_time = 0.0;
prob.initial = [];
