//This file was generated by Finch.

/*

*/
// coef_D1_u_1 = RQ1; // d/dx of trial function
// coef_D1_v_1 = TRQ1; // d/dx of test function
// coef_D2_u_1 = RQ2; // d/dy of trial function
// coef_D2_v_1 = TRQ2; // d/dy of test function
// coef_D3_u_1 = RQ3; // d/dz of trial function
// coef_D3_v_1 = TRQ3; // d/dz of test function

// Allocate temporary storage for each term.
double* out_1 = new double[nPe];
double* out_2 = new double[nPe];
double* out_3 = new double[nPe];

// Trial function factors.
// Multiply by trial function factor: D1(u_1)
DENDRO_TENSOR_IIAX_APPLY_ELEM(nrp,Dg,in,imV1);
DENDRO_TENSOR_IAIX_APPLY_ELEM(nrp,Q1d,imV1,imV2);
DENDRO_TENSOR_AIIX_APPLY_ELEM(nrp,Q1d,imV2,out_1);

// Multiply by trial function factor: D2(u_1)
DENDRO_TENSOR_IIAX_APPLY_ELEM(nrp,Q1d,in,imV1);
DENDRO_TENSOR_IAIX_APPLY_ELEM(nrp,Dg,imV1,imV2);
DENDRO_TENSOR_AIIX_APPLY_ELEM(nrp,Q1d,imV2,out_2);

// Multiply by trial function factor: D3(u_1)
DENDRO_TENSOR_IIAX_APPLY_ELEM(nrp,Q1d,in,imV1);
DENDRO_TENSOR_IAIX_APPLY_ELEM(nrp,Q1d,imV1,imV2);
DENDRO_TENSOR_AIIX_APPLY_ELEM(nrp,Dg,imV2,out_3);

// Multiply quadrature weights, geometric factors and coefficients.
for(unsigned int k=0;k<(eleOrder+1);k++){
    for(unsigned int j=0;j<(eleOrder+1);j++){
        for(unsigned int i=0;i<(eleOrder+1);i++){
out_1[(k*nrp+j)*nrp+i]*=((Jy*Jz/Jx)*-W1d[i]*W1d[j]*W1d[k]);
out_2[(k*nrp+j)*nrp+i]*=((Jx*Jz/Jy)*-W1d[i]*W1d[j]*W1d[k]);
out_3[(k*nrp+j)*nrp+i]*=((Jx*Jy/Jz)*-W1d[i]*W1d[j]*W1d[k]);

        }
    }
}

// multiply by test functions
// Multiply by test function factor: D1(v_1)
DENDRO_TENSOR_IIAX_APPLY_ELEM(nrp,DgT,out_1,imV1);
DENDRO_TENSOR_IAIX_APPLY_ELEM(nrp,QT1d,imV1,imV2);
DENDRO_TENSOR_AIIX_APPLY_ELEM(nrp,QT1d,imV2,out_1);

// Multiply by test function factor: D2(v_1)
DENDRO_TENSOR_IIAX_APPLY_ELEM(nrp,QT1d,out_2,imV1);
DENDRO_TENSOR_IAIX_APPLY_ELEM(nrp,DgT,imV1,imV2);
DENDRO_TENSOR_AIIX_APPLY_ELEM(nrp,QT1d,imV2,out_2);

// Multiply by test function factor: D3(v_1)
DENDRO_TENSOR_IIAX_APPLY_ELEM(nrp,QT1d,out_3,imV1);
DENDRO_TENSOR_IAIX_APPLY_ELEM(nrp,QT1d,imV1,imV2);
DENDRO_TENSOR_AIIX_APPLY_ELEM(nrp,DgT,imV2,out_3);


// Combine all of the terms into the output.
for(unsigned int i=0;i<nPe;i++){
    out[i]=out_1[i]+out_2[i]+out_3[i];
}
delete [] out_1;
delete [] out_2;
delete [] out_3;
