//This file was generated by Finch.

/*

*/
enum VAR{M_UI_u_1=0, M_UI_f_1, M_UI_RHS}; // variables, coefficients, linear part
const char * VAR_NAMES[]={"m_ui_u_1", "m_ui_f_1", "m_uiRHS"};
const unsigned int DOF=3;
const char* prob_bc_type[] = {"Dirichlet"};
int prob_bid[] = {1};
