//This file was generated by Finch.

/*
Generated functions
*/
#include "Genfunction.h"

std::function<double(double)> gridxTox;
std::function<double(double)> gridyToy;
std::function<double(double)> gridzToz;

void set_grid_funs(std::function<double(double)> gx2x, std::function<double(double)> gy2y, std::function<double(double)> gz2z){
    gridxTox = gx2x;
    gridyToy = gy2y;
    gridzToz = gz2z;
}
void genfunction_0(double x, double y, double z, double* var){
    var[0] = 0;
}
void genfunction_1(double x, double y, double z, double* var){
    var[0] = -14 * M_PI * M_PI * sin(3 * M_PI * gridxTox(x)) * sin(2 * M_PI * gridyToy(y)) * sin(M_PI * gridzToz(z));
}
