//This file was generated by Finch.

/*
Problem info
*/
enum VAR{M_UI_U=0,M_UI_F,M_UI_LF}; // variable u, rhs f, linear(f)
const char * VAR_NAMES[]={"m_uiU","m_uiFrhs","m_uiLFrhs"};
const unsigned int DOF=3;
const char* prob_bc_type[] = {"Dirichlet"};
int prob_bid[] = {1};
std::function<void(double,double,double,double*)> bc_u_1 = genfunction_0;
std::function<void(double,double,double,double*)> f_rhs =genfunction_1;
